language: node_js

node_js:
  - 10.14.1

services:
  - postgresql

before_script:
  - psql -c 'create database testdb;' -U postgres
  - yarn db:migrate

after_success:
  - coveralls < coveralls/lcov.info
